DROP TABLE IF EXISTS DEPARTMENT;  
CREATE TABLE DEPARTMENT (  
DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,  
Dept_name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS EMPLOYEE;  
CREATE TABLE EMPLOYEE (  
EMP_ID INT AUTO_INCREMENT PRIMARY KEY,  
FirstName VARCHAR(50) NOT NULL,  
LastName VARCHAR(50) NOT NULL,
Age INT NOT NULL,  
DEPT_ID INT, foreign key(DEPT_ID) references DEPARTMENT(DEPT_ID)
);  

DROP TABLE IF EXISTS ADDRESS;  
CREATE TABLE ADDRESS (  
ADDR_ID INT AUTO_INCREMENT  PRIMARY KEY,  
ADDR VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,  
EMP_ID INT, foreign key(EMP_ID) references EMPLOYEE(EMP_ID)
);